name: flutter_instagram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.2.0
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  email_validator: ^2.0.1
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  device_info_plus: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Bluevinyl
      fonts:
        - asset: assets/fonts/Bluevinyl.otf
  #       - asset: fonts/Schyler-Italic.ttf
